version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: pablofsc/movieflix-app:latest
    container_name: movieflix-app
    networks:
      - movieflix-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: movieflix-nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - movieflix-network

networks:
  movieflix-network:
    driver: bridge
